// GENERATED by tools/codegen/bridge.mjs from schema/bridge.json. DO NOT EDIT.

/* eslint-disable */

export const PROTOCOL_VERSION = 1;

// Records used inside events
export interface TimelineNote {
  readonly start: number;
  readonly length: number;
  readonly pitch: number;
  readonly velocity: number;
}

export interface TimelineClip {
  readonly id: number;
  readonly start: number;
  readonly length: number;
  readonly asset: number;
  readonly sourceOffsetSeconds: number;
  readonly contentOffset: number;
  readonly loopLength: number;
  readonly notes: readonly TimelineNote[];
}

export interface TimelineEffect {
  readonly enabled: boolean;
  readonly values: readonly number[];
}

export interface TimelineSend {
  readonly bus: number;
  readonly levelDb: number;
}

export interface TimelineTrack {
  readonly id: number;
  readonly kind: number;
  readonly name: string;
  readonly volumeDb: number;
  readonly pan: number;
  readonly muted: boolean;
  readonly soloed: boolean;
  readonly clips: readonly TimelineClip[];
  readonly effects: readonly TimelineEffect[];
  readonly sends: readonly TimelineSend[];
}

export interface BusEffect {
  readonly enabled: boolean;
  readonly values: readonly number[];
}

export interface TimelineBus {
  readonly id: number;
  readonly name: string;
  readonly volumeDb: number;
  readonly pan: number;
  readonly muted: boolean;
  readonly effects: readonly BusEffect[];
}

export interface TimelineAsset {
  readonly id: number;
  readonly name: string;
  readonly loaded: boolean;
  readonly missing: boolean;
  readonly loading: boolean;
  readonly durationSeconds: number;
  readonly overview: readonly number[];
}

export interface ProjectAsset {
  readonly id: number;
  readonly name: string;
  readonly clips: number;
  readonly pads: number;
  readonly sampler: boolean;
  readonly missing: boolean;
}

// Intents: UI -> native
export interface AppReady {
  readonly type: 'app.ready';
  readonly payload: {};
}

export interface AudioOpenSettings {
  readonly type: 'audio.openSettings';
  readonly payload: {};
}

export interface ToneSetEnabled {
  readonly type: 'tone.setEnabled';
  readonly payload: {
    readonly enabled: boolean;
  };
}

export interface TransportPlay {
  readonly type: 'transport.play';
  readonly payload: {};
}

export interface TransportStop {
  readonly type: 'transport.stop';
  readonly payload: {};
}

export interface TransportReturnToStart {
  readonly type: 'transport.returnToStart';
  readonly payload: {};
}

export interface TransportSetTempo {
  readonly type: 'transport.setTempo';
  readonly payload: {
    readonly bpm: number;
  };
}

export interface TransportSetCountIn {
  readonly type: 'transport.setCountIn';
  readonly payload: {
    readonly bars: number;
  };
}

export interface MetronomeSetEnabled {
  readonly type: 'metronome.setEnabled';
  readonly payload: {
    readonly enabled: boolean;
  };
}

export interface ParamSet {
  readonly type: 'param.set';
  readonly payload: {
    readonly id: string;
    readonly value: number;
    readonly gesture: number;
  };
}

export interface EditUndo {
  readonly type: 'edit.undo';
  readonly payload: {};
}

export interface EditRedo {
  readonly type: 'edit.redo';
  readonly payload: {};
}

export interface ProjectNew {
  readonly type: 'project.new';
  readonly payload: {};
}

export interface ProjectOpen {
  readonly type: 'project.open';
  readonly payload: {};
}

export interface ProjectSave {
  readonly type: 'project.save';
  readonly payload: {};
}

export interface ProjectSaveAs {
  readonly type: 'project.saveAs';
  readonly payload: {};
}

export interface ProjectRename {
  readonly type: 'project.rename';
  readonly payload: {
    readonly name: string;
  };
}

export interface ProjectExport {
  readonly type: 'project.export';
  readonly payload: {
    readonly format: number;
    readonly sampleRate: number;
  };
}

export interface ProjectCancelExport {
  readonly type: 'project.cancelExport';
  readonly payload: {};
}

export interface NoteOn {
  readonly type: 'note.on';
  readonly payload: {
    readonly note: number;
    readonly velocity: number;
  };
}

export interface NoteOff {
  readonly type: 'note.off';
  readonly payload: {
    readonly note: number;
  };
}

export interface NoteAllOff {
  readonly type: 'note.allOff';
  readonly payload: {};
}

export interface InstrumentSelect {
  readonly type: 'instrument.select';
  readonly payload: {
    readonly instrument: number;
  };
}

export interface SamplerLoad {
  readonly type: 'sampler.load';
  readonly payload: {};
}

export interface DrumsSetStep {
  readonly type: 'drums.setStep';
  readonly payload: {
    readonly clip: number;
    readonly pad: number;
    readonly step: number;
    readonly on: boolean;
    readonly gesture: number;
  };
}

export interface DrumsClear {
  readonly type: 'drums.clear';
  readonly payload: {
    readonly clip: number;
  };
}

export interface DrumsTrigger {
  readonly type: 'drums.trigger';
  readonly payload: {
    readonly pad: number;
    readonly velocity: number;
  };
}

export interface DrumsSetPad {
  readonly type: 'drums.setPad';
  readonly payload: {
    readonly pad: number;
    readonly volumeDb: number;
    readonly pitch: number;
    readonly muted: boolean;
    readonly gesture: number;
  };
}

export interface DrumsLoadPad {
  readonly type: 'drums.loadPad';
  readonly payload: {
    readonly pad: number;
  };
}

export interface DrumsResetPad {
  readonly type: 'drums.resetPad';
  readonly payload: {
    readonly pad: number;
  };
}

export interface DrumsSetKit {
  readonly type: 'drums.setKit';
  readonly payload: {
    readonly kit: number;
  };
}

export interface TransportRecord {
  readonly type: 'transport.record';
  readonly payload: {};
}

export interface TransportCapture {
  readonly type: 'transport.capture';
  readonly payload: {};
}

export interface TransportSeek {
  readonly type: 'transport.seek';
  readonly payload: {
    readonly ticks: number;
  };
}

export interface TransportSetLoop {
  readonly type: 'transport.setLoop';
  readonly payload: {
    readonly enabled: boolean;
    readonly start: number;
    readonly end: number;
  };
}

export interface TrackAdd {
  readonly type: 'track.add';
  readonly payload: {
    readonly kind: number;
  };
}

export interface TrackRemove {
  readonly type: 'track.remove';
  readonly payload: {
    readonly track: number;
  };
}

export interface TrackRename {
  readonly type: 'track.rename';
  readonly payload: {
    readonly track: number;
    readonly name: string;
  };
}

export interface TrackSetVolume {
  readonly type: 'track.setVolume';
  readonly payload: {
    readonly track: number;
    readonly volumeDb: number;
    readonly gesture: number;
  };
}

export interface TrackSetPan {
  readonly type: 'track.setPan';
  readonly payload: {
    readonly track: number;
    readonly pan: number;
    readonly gesture: number;
  };
}

export interface TrackSetMute {
  readonly type: 'track.setMute';
  readonly payload: {
    readonly track: number;
    readonly muted: boolean;
  };
}

export interface TrackSetSolo {
  readonly type: 'track.setSolo';
  readonly payload: {
    readonly track: number;
    readonly soloed: boolean;
  };
}

export interface TrackSetArmed {
  readonly type: 'track.setArmed';
  readonly payload: {
    readonly track: number;
    readonly armed: boolean;
  };
}

export interface TrackSetEffect {
  readonly type: 'track.setEffect';
  readonly payload: {
    readonly track: number;
    readonly effect: number;
    readonly enabled: boolean;
    readonly values: readonly number[];
    readonly gesture: number;
  };
}

export interface TrackImportAudio {
  readonly type: 'track.importAudio';
  readonly payload: {
    readonly track: number;
    readonly ticks: number;
  };
}

export interface AssetLocate {
  readonly type: 'asset.locate';
  readonly payload: {
    readonly asset: number;
  };
}

export interface AssetRemove {
  readonly type: 'asset.remove';
  readonly payload: {
    readonly asset: number;
  };
}

export interface AssetRemoveUnused {
  readonly type: 'asset.removeUnused';
  readonly payload: {};
}

export interface ClipCreate {
  readonly type: 'clip.create';
  readonly payload: {
    readonly track: number;
    readonly start: number;
    readonly length: number;
  };
}

export interface ClipMove {
  readonly type: 'clip.move';
  readonly payload: {
    readonly clip: number;
    readonly track: number;
    readonly start: number;
    readonly gesture: number;
  };
}

export interface ClipResize {
  readonly type: 'clip.resize';
  readonly payload: {
    readonly clip: number;
    readonly edge: number;
    readonly ticks: number;
    readonly gesture: number;
  };
}

export interface ClipSplit {
  readonly type: 'clip.split';
  readonly payload: {
    readonly clip: number;
    readonly ticks: number;
  };
}

export interface ClipRemove {
  readonly type: 'clip.remove';
  readonly payload: {
    readonly clip: number;
  };
}

export interface ClipDuplicate {
  readonly type: 'clip.duplicate';
  readonly payload: {
    readonly clip: number;
  };
}

export interface ClipSetLoop {
  readonly type: 'clip.setLoop';
  readonly payload: {
    readonly clip: number;
    readonly enabled: boolean;
  };
}

export interface ClipAddNote {
  readonly type: 'clip.addNote';
  readonly payload: {
    readonly clip: number;
    readonly start: number;
    readonly length: number;
    readonly pitch: number;
    readonly velocity: number;
  };
}

export interface ClipRemoveNote {
  readonly type: 'clip.removeNote';
  readonly payload: {
    readonly clip: number;
    readonly start: number;
    readonly pitch: number;
  };
}

export interface ClipEditNote {
  readonly type: 'clip.editNote';
  readonly payload: {
    readonly clip: number;
    readonly fromStart: number;
    readonly fromPitch: number;
    readonly start: number;
    readonly length: number;
    readonly pitch: number;
    readonly gesture: number;
  };
}

export interface BusAdd {
  readonly type: 'bus.add';
  readonly payload: {};
}

export interface BusRemove {
  readonly type: 'bus.remove';
  readonly payload: {
    readonly bus: number;
  };
}

export interface BusRename {
  readonly type: 'bus.rename';
  readonly payload: {
    readonly bus: number;
    readonly name: string;
  };
}

export interface BusSetVolume {
  readonly type: 'bus.setVolume';
  readonly payload: {
    readonly bus: number;
    readonly volumeDb: number;
    readonly gesture: number;
  };
}

export interface BusSetPan {
  readonly type: 'bus.setPan';
  readonly payload: {
    readonly bus: number;
    readonly pan: number;
    readonly gesture: number;
  };
}

export interface BusSetMute {
  readonly type: 'bus.setMute';
  readonly payload: {
    readonly bus: number;
    readonly muted: boolean;
  };
}

export interface BusSetEffect {
  readonly type: 'bus.setEffect';
  readonly payload: {
    readonly bus: number;
    readonly effect: number;
    readonly enabled: boolean;
    readonly values: readonly number[];
    readonly gesture: number;
  };
}

export interface TrackSetSend {
  readonly type: 'track.setSend';
  readonly payload: {
    readonly track: number;
    readonly bus: number;
    readonly levelDb: number;
    readonly gesture: number;
  };
}

export type Intent = AppReady | AudioOpenSettings | ToneSetEnabled | TransportPlay | TransportStop | TransportReturnToStart | TransportSetTempo | TransportSetCountIn | MetronomeSetEnabled | ParamSet | EditUndo | EditRedo | ProjectNew | ProjectOpen | ProjectSave | ProjectSaveAs | ProjectRename | ProjectExport | ProjectCancelExport | NoteOn | NoteOff | NoteAllOff | InstrumentSelect | SamplerLoad | DrumsSetStep | DrumsClear | DrumsTrigger | DrumsSetPad | DrumsLoadPad | DrumsResetPad | DrumsSetKit | TransportRecord | TransportCapture | TransportSeek | TransportSetLoop | TrackAdd | TrackRemove | TrackRename | TrackSetVolume | TrackSetPan | TrackSetMute | TrackSetSolo | TrackSetArmed | TrackSetEffect | TrackImportAudio | AssetLocate | AssetRemove | AssetRemoveUnused | ClipCreate | ClipMove | ClipResize | ClipSplit | ClipRemove | ClipDuplicate | ClipSetLoop | ClipAddNote | ClipRemoveNote | ClipEditNote | BusAdd | BusRemove | BusRename | BusSetVolume | BusSetPan | BusSetMute | BusSetEffect | TrackSetSend;

// Events: native -> UI
export interface EngineStatus {
  readonly type: 'engine.status';
  readonly payload: {
    readonly deviceName: string;
    readonly sampleRate: number;
    readonly bufferSize: number;
    readonly outputLatencyMs: number;
    readonly inputName: string;
    readonly inputChannels: number;
    readonly roundTripLatencyMs: number;
    readonly error: string;
    readonly toneEnabled: boolean;
  };
}

export interface EngineMeters {
  readonly type: 'engine.meters';
  readonly payload: {
    readonly peak: number;
    readonly inputPeak: number;
    readonly limiterDb: number;
  };
}

export interface TransportState {
  readonly type: 'transport.state';
  readonly payload: {
    readonly playing: boolean;
    readonly bpm: number;
    readonly numerator: number;
    readonly denominator: number;
    readonly countInBars: number;
    readonly metronomeEnabled: boolean;
    readonly recording: boolean;
    readonly armedTrack: number;
    readonly captureAvailable: boolean;
    readonly loopEnabled: boolean;
    readonly loopStart: number;
    readonly loopEnd: number;
  };
}

export interface TransportPosition {
  readonly type: 'transport.position';
  readonly payload: {
    readonly bar: number;
    readonly beat: number;
    readonly countingIn: boolean;
    readonly ticks: number;
  };
}

export interface ParamValue {
  readonly type: 'param.value';
  readonly payload: {
    readonly id: string;
    readonly value: number;
  };
}

export interface HistoryState {
  readonly type: 'history.state';
  readonly payload: {
    readonly canUndo: boolean;
    readonly canRedo: boolean;
    readonly undoLabel: string;
    readonly redoLabel: string;
  };
}

export interface ProjectState {
  readonly type: 'project.state';
  readonly payload: {
    readonly name: string;
    readonly dirty: boolean;
    readonly hasLocation: boolean;
  };
}

export interface ExportState {
  readonly type: 'export.state';
  readonly payload: {
    readonly running: boolean;
    readonly progress: number;
  };
}

export interface AppNotice {
  readonly type: 'app.notice';
  readonly payload: {
    readonly level: number;
    readonly message: string;
  };
}

export interface InstrumentState {
  readonly type: 'instrument.state';
  readonly payload: {
    readonly instrument: number;
  };
}

export interface SamplerState {
  readonly type: 'sampler.state';
  readonly payload: {
    readonly name: string;
    readonly loaded: boolean;
    readonly missing: boolean;
    readonly loading: boolean;
    readonly durationSeconds: number;
    readonly overview: readonly number[];
  };
}

export interface DrumsKit {
  readonly type: 'drums.kit';
  readonly payload: {
    readonly kit: number;
  };
}

export interface DrumsPad {
  readonly type: 'drums.pad';
  readonly payload: {
    readonly pad: number;
    readonly name: string;
    readonly volumeDb: number;
    readonly pitch: number;
    readonly muted: boolean;
    readonly custom: boolean;
    readonly missing: boolean;
  };
}

export interface TimelineState {
  readonly type: 'timeline.state';
  readonly payload: {
    readonly tracks: readonly TimelineTrack[];
    readonly buses: readonly TimelineBus[];
  };
}

export interface TimelineAssets {
  readonly type: 'timeline.assets';
  readonly payload: {
    readonly assets: readonly TimelineAsset[];
  };
}

export interface ProjectAssets {
  readonly type: 'project.assets';
  readonly payload: {
    readonly assets: readonly ProjectAsset[];
  };
}

export interface TimelinePeaks {
  readonly type: 'timeline.peaks';
  readonly payload: {
    readonly asset: number;
    readonly peaksPerSecond: number;
    readonly data: string;
  };
}

export type NativeEvent = EngineStatus | EngineMeters | TransportState | TransportPosition | ParamValue | HistoryState | ProjectState | ExportState | AppNotice | InstrumentState | SamplerState | DrumsKit | DrumsPad | TimelineState | TimelineAssets | ProjectAssets | TimelinePeaks;
export type NativeEventType = NativeEvent['type'];

/** Payload type for each native event type. */
export interface NativeEventPayloads {
  'engine.status': EngineStatus['payload'];
  'engine.meters': EngineMeters['payload'];
  'transport.state': TransportState['payload'];
  'transport.position': TransportPosition['payload'];
  'param.value': ParamValue['payload'];
  'history.state': HistoryState['payload'];
  'project.state': ProjectState['payload'];
  'export.state': ExportState['payload'];
  'app.notice': AppNotice['payload'];
  'instrument.state': InstrumentState['payload'];
  'sampler.state': SamplerState['payload'];
  'drums.kit': DrumsKit['payload'];
  'drums.pad': DrumsPad['payload'];
  'timeline.state': TimelineState['payload'];
  'timeline.assets': TimelineAssets['payload'];
  'project.assets': ProjectAssets['payload'];
  'timeline.peaks': TimelinePeaks['payload'];
}

type Payload = Record<string, unknown>;

function isPayload(value: unknown): value is Payload {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isNumberArray(value: unknown, min: number, max: number, maxItems: number): boolean {
  return (
    Array.isArray(value) &&
    value.length <= maxItems &&
    value.every((item: unknown) => typeof item === 'number' && Number.isFinite(item) && item >= min && item <= max)
  );
}

function hasOnlyKeys(payload: Payload, keys: readonly string[]): boolean {
  const actual = Object.keys(payload);
  return actual.length === keys.length && keys.every((key) => Object.hasOwn(payload, key));
}

function isList(value: unknown, maxItems: number, isItem: (item: unknown) => boolean): boolean {
  return Array.isArray(value) && value.length <= maxItems && value.every((item: unknown) => isItem(item));
}

function isTimelineNote(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['start', 'length', 'pitch', 'velocity']) &&
    Number.isInteger(payload['start']) && (payload['start'] as number) >= 0 && (payload['start'] as number) <= 38400000 &&
    Number.isInteger(payload['length']) && (payload['length'] as number) >= 1 && (payload['length'] as number) <= 38400000 &&
    Number.isInteger(payload['pitch']) && (payload['pitch'] as number) >= 0 && (payload['pitch'] as number) <= 127 &&
    typeof payload['velocity'] === 'number' && Number.isFinite(payload['velocity']) && payload['velocity'] >= 0 && payload['velocity'] <= 1
  );
}

function isTimelineClip(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['id', 'start', 'length', 'asset', 'sourceOffsetSeconds', 'contentOffset', 'loopLength', 'notes']) &&
    Number.isInteger(payload['id']) && (payload['id'] as number) >= 1 && (payload['id'] as number) <= 2147483647 &&
    Number.isInteger(payload['start']) && (payload['start'] as number) >= 0 && (payload['start'] as number) <= 38400000 &&
    Number.isInteger(payload['length']) && (payload['length'] as number) >= 1 && (payload['length'] as number) <= 38400000 &&
    Number.isInteger(payload['asset']) && (payload['asset'] as number) >= 0 && (payload['asset'] as number) <= 2147483647 &&
    typeof payload['sourceOffsetSeconds'] === 'number' && Number.isFinite(payload['sourceOffsetSeconds']) && payload['sourceOffsetSeconds'] >= 0 && payload['sourceOffsetSeconds'] <= 86400 &&
    Number.isInteger(payload['contentOffset']) && (payload['contentOffset'] as number) >= 0 && (payload['contentOffset'] as number) <= 38400000 &&
    Number.isInteger(payload['loopLength']) && (payload['loopLength'] as number) >= 0 && (payload['loopLength'] as number) <= 38400000 &&
    isList(payload['notes'], 4096, isTimelineNote)
  );
}

function isTimelineEffect(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['enabled', 'values']) &&
    typeof payload['enabled'] === 'boolean' &&
    isNumberArray(payload['values'], -100000, 100000, 8)
  );
}

function isTimelineSend(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['bus', 'levelDb']) &&
    Number.isInteger(payload['bus']) && (payload['bus'] as number) >= 1 && (payload['bus'] as number) <= 2147483647 &&
    typeof payload['levelDb'] === 'number' && Number.isFinite(payload['levelDb']) && payload['levelDb'] >= -60 && payload['levelDb'] <= 6
  );
}

function isTimelineTrack(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['id', 'kind', 'name', 'volumeDb', 'pan', 'muted', 'soloed', 'clips', 'effects', 'sends']) &&
    Number.isInteger(payload['id']) && (payload['id'] as number) >= 1 && (payload['id'] as number) <= 2147483647 &&
    Number.isInteger(payload['kind']) && (payload['kind'] as number) >= 0 && (payload['kind'] as number) <= 3 &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['volumeDb'] === 'number' && Number.isFinite(payload['volumeDb']) && payload['volumeDb'] >= -60 && payload['volumeDb'] <= 6 &&
    typeof payload['pan'] === 'number' && Number.isFinite(payload['pan']) && payload['pan'] >= -1 && payload['pan'] <= 1 &&
    typeof payload['muted'] === 'boolean' &&
    typeof payload['soloed'] === 'boolean' &&
    isList(payload['clips'], 512, isTimelineClip) &&
    isList(payload['effects'], 6, isTimelineEffect) &&
    isList(payload['sends'], 8, isTimelineSend)
  );
}

function isBusEffect(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['enabled', 'values']) &&
    typeof payload['enabled'] === 'boolean' &&
    isNumberArray(payload['values'], -100000, 100000, 8)
  );
}

function isTimelineBus(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['id', 'name', 'volumeDb', 'pan', 'muted', 'effects']) &&
    Number.isInteger(payload['id']) && (payload['id'] as number) >= 1 && (payload['id'] as number) <= 2147483647 &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['volumeDb'] === 'number' && Number.isFinite(payload['volumeDb']) && payload['volumeDb'] >= -60 && payload['volumeDb'] <= 6 &&
    typeof payload['pan'] === 'number' && Number.isFinite(payload['pan']) && payload['pan'] >= -1 && payload['pan'] <= 1 &&
    typeof payload['muted'] === 'boolean' &&
    isList(payload['effects'], 6, isBusEffect)
  );
}

function isTimelineAsset(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['id', 'name', 'loaded', 'missing', 'loading', 'durationSeconds', 'overview']) &&
    Number.isInteger(payload['id']) && (payload['id'] as number) >= 1 && (payload['id'] as number) <= 2147483647 &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['loaded'] === 'boolean' &&
    typeof payload['missing'] === 'boolean' &&
    typeof payload['loading'] === 'boolean' &&
    typeof payload['durationSeconds'] === 'number' && Number.isFinite(payload['durationSeconds']) && payload['durationSeconds'] >= 0 && payload['durationSeconds'] <= 100000 &&
    isNumberArray(payload['overview'], 0, 1, 512)
  );
}

function isProjectAsset(value: unknown): boolean {
  if (!isPayload(value)) return false;
  const payload = value;
  return (
    hasOnlyKeys(payload, ['id', 'name', 'clips', 'pads', 'sampler', 'missing']) &&
    Number.isInteger(payload['id']) && (payload['id'] as number) >= 1 && (payload['id'] as number) <= 2147483647 &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    Number.isInteger(payload['clips']) && (payload['clips'] as number) >= 0 && (payload['clips'] as number) <= 1000000 &&
    Number.isInteger(payload['pads']) && (payload['pads'] as number) >= 0 && (payload['pads'] as number) <= 16 &&
    typeof payload['sampler'] === 'boolean' &&
    typeof payload['missing'] === 'boolean'
  );
}

const eventValidators: Record<NativeEventType, (payload: Payload) => boolean> = {
  'engine.status': (payload) =>
    hasOnlyKeys(payload, ['deviceName', 'sampleRate', 'bufferSize', 'outputLatencyMs', 'inputName', 'inputChannels', 'roundTripLatencyMs', 'error', 'toneEnabled']) &&
    typeof payload['deviceName'] === 'string' && payload['deviceName'].length <= 256 &&
    typeof payload['sampleRate'] === 'number' && Number.isFinite(payload['sampleRate']) && payload['sampleRate'] >= 0 && payload['sampleRate'] <= 768000 &&
    Number.isInteger(payload['bufferSize']) && (payload['bufferSize'] as number) >= 0 && (payload['bufferSize'] as number) <= 65536 &&
    typeof payload['outputLatencyMs'] === 'number' && Number.isFinite(payload['outputLatencyMs']) && payload['outputLatencyMs'] >= 0 && payload['outputLatencyMs'] <= 10000 &&
    typeof payload['inputName'] === 'string' && payload['inputName'].length <= 256 &&
    Number.isInteger(payload['inputChannels']) && (payload['inputChannels'] as number) >= 0 && (payload['inputChannels'] as number) <= 2 &&
    typeof payload['roundTripLatencyMs'] === 'number' && Number.isFinite(payload['roundTripLatencyMs']) && payload['roundTripLatencyMs'] >= 0 && payload['roundTripLatencyMs'] <= 10000 &&
    typeof payload['error'] === 'string' && payload['error'].length <= 1024 &&
    typeof payload['toneEnabled'] === 'boolean',
  'engine.meters': (payload) =>
    hasOnlyKeys(payload, ['peak', 'inputPeak', 'limiterDb']) &&
    typeof payload['peak'] === 'number' && Number.isFinite(payload['peak']) && payload['peak'] >= 0 && payload['peak'] <= 1 &&
    typeof payload['inputPeak'] === 'number' && Number.isFinite(payload['inputPeak']) && payload['inputPeak'] >= 0 && payload['inputPeak'] <= 1 &&
    typeof payload['limiterDb'] === 'number' && Number.isFinite(payload['limiterDb']) && payload['limiterDb'] >= -60 && payload['limiterDb'] <= 0,
  'transport.state': (payload) =>
    hasOnlyKeys(payload, ['playing', 'bpm', 'numerator', 'denominator', 'countInBars', 'metronomeEnabled', 'recording', 'armedTrack', 'captureAvailable', 'loopEnabled', 'loopStart', 'loopEnd']) &&
    typeof payload['playing'] === 'boolean' &&
    typeof payload['bpm'] === 'number' && Number.isFinite(payload['bpm']) && payload['bpm'] >= 20 && payload['bpm'] <= 300 &&
    Number.isInteger(payload['numerator']) && (payload['numerator'] as number) >= 1 && (payload['numerator'] as number) <= 32 &&
    Number.isInteger(payload['denominator']) && (payload['denominator'] as number) >= 1 && (payload['denominator'] as number) <= 16 &&
    Number.isInteger(payload['countInBars']) && (payload['countInBars'] as number) >= 0 && (payload['countInBars'] as number) <= 4 &&
    typeof payload['metronomeEnabled'] === 'boolean' &&
    typeof payload['recording'] === 'boolean' &&
    Number.isInteger(payload['armedTrack']) && (payload['armedTrack'] as number) >= 0 && (payload['armedTrack'] as number) <= 2147483647 &&
    typeof payload['captureAvailable'] === 'boolean' &&
    typeof payload['loopEnabled'] === 'boolean' &&
    Number.isInteger(payload['loopStart']) && (payload['loopStart'] as number) >= 0 && (payload['loopStart'] as number) <= 38400000 &&
    Number.isInteger(payload['loopEnd']) && (payload['loopEnd'] as number) >= 0 && (payload['loopEnd'] as number) <= 38400000,
  'transport.position': (payload) =>
    hasOnlyKeys(payload, ['bar', 'beat', 'countingIn', 'ticks']) &&
    Number.isInteger(payload['bar']) && (payload['bar'] as number) >= -1000 && (payload['bar'] as number) <= 100000000 &&
    Number.isInteger(payload['beat']) && (payload['beat'] as number) >= 1 && (payload['beat'] as number) <= 32 &&
    typeof payload['countingIn'] === 'boolean' &&
    Number.isInteger(payload['ticks']) && (payload['ticks'] as number) >= -10000000 && (payload['ticks'] as number) <= 76800000,
  'param.value': (payload) =>
    hasOnlyKeys(payload, ['id', 'value']) &&
    typeof payload['id'] === 'string' && payload['id'].length <= 64 &&
    typeof payload['value'] === 'number' && Number.isFinite(payload['value']) && payload['value'] >= -1000000 && payload['value'] <= 1000000,
  'history.state': (payload) =>
    hasOnlyKeys(payload, ['canUndo', 'canRedo', 'undoLabel', 'redoLabel']) &&
    typeof payload['canUndo'] === 'boolean' &&
    typeof payload['canRedo'] === 'boolean' &&
    typeof payload['undoLabel'] === 'string' && payload['undoLabel'].length <= 64 &&
    typeof payload['redoLabel'] === 'string' && payload['redoLabel'].length <= 64,
  'project.state': (payload) =>
    hasOnlyKeys(payload, ['name', 'dirty', 'hasLocation']) &&
    typeof payload['name'] === 'string' && payload['name'].length <= 512 &&
    typeof payload['dirty'] === 'boolean' &&
    typeof payload['hasLocation'] === 'boolean',
  'export.state': (payload) =>
    hasOnlyKeys(payload, ['running', 'progress']) &&
    typeof payload['running'] === 'boolean' &&
    typeof payload['progress'] === 'number' && Number.isFinite(payload['progress']) && payload['progress'] >= 0 && payload['progress'] <= 1,
  'app.notice': (payload) =>
    hasOnlyKeys(payload, ['level', 'message']) &&
    Number.isInteger(payload['level']) && (payload['level'] as number) >= 0 && (payload['level'] as number) <= 2 &&
    typeof payload['message'] === 'string' && payload['message'].length <= 1024,
  'instrument.state': (payload) =>
    hasOnlyKeys(payload, ['instrument']) &&
    Number.isInteger(payload['instrument']) && (payload['instrument'] as number) >= 0 && (payload['instrument'] as number) <= 2,
  'sampler.state': (payload) =>
    hasOnlyKeys(payload, ['name', 'loaded', 'missing', 'loading', 'durationSeconds', 'overview']) &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['loaded'] === 'boolean' &&
    typeof payload['missing'] === 'boolean' &&
    typeof payload['loading'] === 'boolean' &&
    typeof payload['durationSeconds'] === 'number' && Number.isFinite(payload['durationSeconds']) && payload['durationSeconds'] >= 0 && payload['durationSeconds'] <= 100000 &&
    isNumberArray(payload['overview'], 0, 1, 512),
  'drums.kit': (payload) =>
    hasOnlyKeys(payload, ['kit']) &&
    Number.isInteger(payload['kit']) && (payload['kit'] as number) >= 0 && (payload['kit'] as number) <= 4,
  'drums.pad': (payload) =>
    hasOnlyKeys(payload, ['pad', 'name', 'volumeDb', 'pitch', 'muted', 'custom', 'missing']) &&
    Number.isInteger(payload['pad']) && (payload['pad'] as number) >= 0 && (payload['pad'] as number) <= 15 &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['volumeDb'] === 'number' && Number.isFinite(payload['volumeDb']) && payload['volumeDb'] >= -60 && payload['volumeDb'] <= 6 &&
    typeof payload['pitch'] === 'number' && Number.isFinite(payload['pitch']) && payload['pitch'] >= -24 && payload['pitch'] <= 24 &&
    typeof payload['muted'] === 'boolean' &&
    typeof payload['custom'] === 'boolean' &&
    typeof payload['missing'] === 'boolean',
  'timeline.state': (payload) =>
    hasOnlyKeys(payload, ['tracks', 'buses']) &&
    isList(payload['tracks'], 64, isTimelineTrack) &&
    isList(payload['buses'], 8, isTimelineBus),
  'timeline.assets': (payload) =>
    hasOnlyKeys(payload, ['assets']) &&
    isList(payload['assets'], 1024, isTimelineAsset),
  'project.assets': (payload) =>
    hasOnlyKeys(payload, ['assets']) &&
    isList(payload['assets'], 1024, isProjectAsset),
  'timeline.peaks': (payload) =>
    hasOnlyKeys(payload, ['asset', 'peaksPerSecond', 'data']) &&
    Number.isInteger(payload['asset']) && (payload['asset'] as number) >= 1 && (payload['asset'] as number) <= 2147483647 &&
    typeof payload['peaksPerSecond'] === 'number' && Number.isFinite(payload['peaksPerSecond']) && payload['peaksPerSecond'] >= 1 && payload['peaksPerSecond'] <= 1000 &&
    typeof payload['data'] === 'string' && payload['data'].length <= 180000,
};

/** Strictly validates a message received from native code. Returns null if it is malformed. */
export function parseNativeEvent(message: unknown): NativeEvent | null {
  if (!isPayload(message) || !hasOnlyKeys(message, ['type', 'payload'])) return null;
  const { type, payload } = message;
  if (typeof type !== 'string' || !Object.hasOwn(eventValidators, type) || !isPayload(payload)) return null;
  return eventValidators[type as NativeEventType](payload) ? (message as unknown as NativeEvent) : null;
}
