// GENERATED by tools/codegen/bridge.mjs from schema/bridge.json. DO NOT EDIT.

/* eslint-disable */

export const PROTOCOL_VERSION = 1;

// Intents: UI -> native
export interface AppReady {
  readonly type: 'app.ready';
  readonly payload: {};
}

export interface AudioOpenSettings {
  readonly type: 'audio.openSettings';
  readonly payload: {};
}

export interface ToneSetEnabled {
  readonly type: 'tone.setEnabled';
  readonly payload: {
    readonly enabled: boolean;
  };
}

export interface TransportPlay {
  readonly type: 'transport.play';
  readonly payload: {};
}

export interface TransportStop {
  readonly type: 'transport.stop';
  readonly payload: {};
}

export interface TransportReturnToStart {
  readonly type: 'transport.returnToStart';
  readonly payload: {};
}

export interface TransportSetTempo {
  readonly type: 'transport.setTempo';
  readonly payload: {
    readonly bpm: number;
  };
}

export interface TransportSetCountIn {
  readonly type: 'transport.setCountIn';
  readonly payload: {
    readonly bars: number;
  };
}

export interface MetronomeSetEnabled {
  readonly type: 'metronome.setEnabled';
  readonly payload: {
    readonly enabled: boolean;
  };
}

export interface ParamSet {
  readonly type: 'param.set';
  readonly payload: {
    readonly id: string;
    readonly value: number;
    readonly gesture: number;
  };
}

export interface EditUndo {
  readonly type: 'edit.undo';
  readonly payload: {};
}

export interface EditRedo {
  readonly type: 'edit.redo';
  readonly payload: {};
}

export interface ProjectNew {
  readonly type: 'project.new';
  readonly payload: {};
}

export interface ProjectOpen {
  readonly type: 'project.open';
  readonly payload: {};
}

export interface ProjectSave {
  readonly type: 'project.save';
  readonly payload: {};
}

export interface ProjectSaveAs {
  readonly type: 'project.saveAs';
  readonly payload: {};
}

export interface ProjectRename {
  readonly type: 'project.rename';
  readonly payload: {
    readonly name: string;
  };
}

export interface NoteOn {
  readonly type: 'note.on';
  readonly payload: {
    readonly note: number;
    readonly velocity: number;
  };
}

export interface NoteOff {
  readonly type: 'note.off';
  readonly payload: {
    readonly note: number;
  };
}

export interface NoteAllOff {
  readonly type: 'note.allOff';
  readonly payload: {};
}

export interface InstrumentSelect {
  readonly type: 'instrument.select';
  readonly payload: {
    readonly instrument: number;
  };
}

export interface SamplerLoad {
  readonly type: 'sampler.load';
  readonly payload: {};
}

export interface DrumsSetStep {
  readonly type: 'drums.setStep';
  readonly payload: {
    readonly pad: number;
    readonly step: number;
    readonly on: boolean;
    readonly gesture: number;
  };
}

export interface DrumsClear {
  readonly type: 'drums.clear';
  readonly payload: {};
}

export interface DrumsTrigger {
  readonly type: 'drums.trigger';
  readonly payload: {
    readonly pad: number;
    readonly velocity: number;
  };
}

export interface DrumsSetPad {
  readonly type: 'drums.setPad';
  readonly payload: {
    readonly pad: number;
    readonly volumeDb: number;
    readonly pitch: number;
    readonly muted: boolean;
    readonly gesture: number;
  };
}

export interface DrumsLoadPad {
  readonly type: 'drums.loadPad';
  readonly payload: {
    readonly pad: number;
  };
}

export interface DrumsResetPad {
  readonly type: 'drums.resetPad';
  readonly payload: {
    readonly pad: number;
  };
}

export type Intent = AppReady | AudioOpenSettings | ToneSetEnabled | TransportPlay | TransportStop | TransportReturnToStart | TransportSetTempo | TransportSetCountIn | MetronomeSetEnabled | ParamSet | EditUndo | EditRedo | ProjectNew | ProjectOpen | ProjectSave | ProjectSaveAs | ProjectRename | NoteOn | NoteOff | NoteAllOff | InstrumentSelect | SamplerLoad | DrumsSetStep | DrumsClear | DrumsTrigger | DrumsSetPad | DrumsLoadPad | DrumsResetPad;

// Events: native -> UI
export interface EngineStatus {
  readonly type: 'engine.status';
  readonly payload: {
    readonly deviceName: string;
    readonly sampleRate: number;
    readonly bufferSize: number;
    readonly outputLatencyMs: number;
    readonly error: string;
    readonly toneEnabled: boolean;
  };
}

export interface EngineMeters {
  readonly type: 'engine.meters';
  readonly payload: {
    readonly peak: number;
  };
}

export interface TransportState {
  readonly type: 'transport.state';
  readonly payload: {
    readonly playing: boolean;
    readonly bpm: number;
    readonly numerator: number;
    readonly denominator: number;
    readonly countInBars: number;
    readonly metronomeEnabled: boolean;
  };
}

export interface TransportPosition {
  readonly type: 'transport.position';
  readonly payload: {
    readonly bar: number;
    readonly beat: number;
    readonly countingIn: boolean;
    readonly step: number;
  };
}

export interface ParamValue {
  readonly type: 'param.value';
  readonly payload: {
    readonly id: string;
    readonly value: number;
  };
}

export interface HistoryState {
  readonly type: 'history.state';
  readonly payload: {
    readonly canUndo: boolean;
    readonly canRedo: boolean;
    readonly undoLabel: string;
    readonly redoLabel: string;
  };
}

export interface ProjectState {
  readonly type: 'project.state';
  readonly payload: {
    readonly name: string;
    readonly dirty: boolean;
    readonly hasLocation: boolean;
  };
}

export interface AppNotice {
  readonly type: 'app.notice';
  readonly payload: {
    readonly level: number;
    readonly message: string;
  };
}

export interface InstrumentState {
  readonly type: 'instrument.state';
  readonly payload: {
    readonly instrument: number;
  };
}

export interface SamplerState {
  readonly type: 'sampler.state';
  readonly payload: {
    readonly name: string;
    readonly loaded: boolean;
    readonly missing: boolean;
    readonly loading: boolean;
    readonly durationSeconds: number;
    readonly overview: readonly number[];
  };
}

export interface DrumsPattern {
  readonly type: 'drums.pattern';
  readonly payload: {
    readonly steps: readonly number[];
  };
}

export interface DrumsPad {
  readonly type: 'drums.pad';
  readonly payload: {
    readonly pad: number;
    readonly name: string;
    readonly volumeDb: number;
    readonly pitch: number;
    readonly muted: boolean;
    readonly custom: boolean;
    readonly missing: boolean;
  };
}

export type NativeEvent = EngineStatus | EngineMeters | TransportState | TransportPosition | ParamValue | HistoryState | ProjectState | AppNotice | InstrumentState | SamplerState | DrumsPattern | DrumsPad;
export type NativeEventType = NativeEvent['type'];

/** Payload type for each native event type. */
export interface NativeEventPayloads {
  'engine.status': EngineStatus['payload'];
  'engine.meters': EngineMeters['payload'];
  'transport.state': TransportState['payload'];
  'transport.position': TransportPosition['payload'];
  'param.value': ParamValue['payload'];
  'history.state': HistoryState['payload'];
  'project.state': ProjectState['payload'];
  'app.notice': AppNotice['payload'];
  'instrument.state': InstrumentState['payload'];
  'sampler.state': SamplerState['payload'];
  'drums.pattern': DrumsPattern['payload'];
  'drums.pad': DrumsPad['payload'];
}

type Payload = Record<string, unknown>;

function isPayload(value: unknown): value is Payload {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isNumberArray(value: unknown, min: number, max: number, maxItems: number): boolean {
  return (
    Array.isArray(value) &&
    value.length <= maxItems &&
    value.every((item: unknown) => typeof item === 'number' && Number.isFinite(item) && item >= min && item <= max)
  );
}

function hasOnlyKeys(payload: Payload, keys: readonly string[]): boolean {
  const actual = Object.keys(payload);
  return actual.length === keys.length && keys.every((key) => Object.hasOwn(payload, key));
}

const eventValidators: Record<NativeEventType, (payload: Payload) => boolean> = {
  'engine.status': (payload) =>
    hasOnlyKeys(payload, ['deviceName', 'sampleRate', 'bufferSize', 'outputLatencyMs', 'error', 'toneEnabled']) &&
    typeof payload['deviceName'] === 'string' && payload['deviceName'].length <= 256 &&
    typeof payload['sampleRate'] === 'number' && Number.isFinite(payload['sampleRate']) && payload['sampleRate'] >= 0 && payload['sampleRate'] <= 768000 &&
    Number.isInteger(payload['bufferSize']) && (payload['bufferSize'] as number) >= 0 && (payload['bufferSize'] as number) <= 65536 &&
    typeof payload['outputLatencyMs'] === 'number' && Number.isFinite(payload['outputLatencyMs']) && payload['outputLatencyMs'] >= 0 && payload['outputLatencyMs'] <= 10000 &&
    typeof payload['error'] === 'string' && payload['error'].length <= 1024 &&
    typeof payload['toneEnabled'] === 'boolean',
  'engine.meters': (payload) =>
    hasOnlyKeys(payload, ['peak']) &&
    typeof payload['peak'] === 'number' && Number.isFinite(payload['peak']) && payload['peak'] >= 0 && payload['peak'] <= 1,
  'transport.state': (payload) =>
    hasOnlyKeys(payload, ['playing', 'bpm', 'numerator', 'denominator', 'countInBars', 'metronomeEnabled']) &&
    typeof payload['playing'] === 'boolean' &&
    typeof payload['bpm'] === 'number' && Number.isFinite(payload['bpm']) && payload['bpm'] >= 20 && payload['bpm'] <= 300 &&
    Number.isInteger(payload['numerator']) && (payload['numerator'] as number) >= 1 && (payload['numerator'] as number) <= 32 &&
    Number.isInteger(payload['denominator']) && (payload['denominator'] as number) >= 1 && (payload['denominator'] as number) <= 16 &&
    Number.isInteger(payload['countInBars']) && (payload['countInBars'] as number) >= 0 && (payload['countInBars'] as number) <= 4 &&
    typeof payload['metronomeEnabled'] === 'boolean',
  'transport.position': (payload) =>
    hasOnlyKeys(payload, ['bar', 'beat', 'countingIn', 'step']) &&
    Number.isInteger(payload['bar']) && (payload['bar'] as number) >= -1000 && (payload['bar'] as number) <= 100000000 &&
    Number.isInteger(payload['beat']) && (payload['beat'] as number) >= 1 && (payload['beat'] as number) <= 32 &&
    typeof payload['countingIn'] === 'boolean' &&
    Number.isInteger(payload['step']) && (payload['step'] as number) >= 0 && (payload['step'] as number) <= 15,
  'param.value': (payload) =>
    hasOnlyKeys(payload, ['id', 'value']) &&
    typeof payload['id'] === 'string' && payload['id'].length <= 64 &&
    typeof payload['value'] === 'number' && Number.isFinite(payload['value']) && payload['value'] >= -1000000 && payload['value'] <= 1000000,
  'history.state': (payload) =>
    hasOnlyKeys(payload, ['canUndo', 'canRedo', 'undoLabel', 'redoLabel']) &&
    typeof payload['canUndo'] === 'boolean' &&
    typeof payload['canRedo'] === 'boolean' &&
    typeof payload['undoLabel'] === 'string' && payload['undoLabel'].length <= 64 &&
    typeof payload['redoLabel'] === 'string' && payload['redoLabel'].length <= 64,
  'project.state': (payload) =>
    hasOnlyKeys(payload, ['name', 'dirty', 'hasLocation']) &&
    typeof payload['name'] === 'string' && payload['name'].length <= 512 &&
    typeof payload['dirty'] === 'boolean' &&
    typeof payload['hasLocation'] === 'boolean',
  'app.notice': (payload) =>
    hasOnlyKeys(payload, ['level', 'message']) &&
    Number.isInteger(payload['level']) && (payload['level'] as number) >= 0 && (payload['level'] as number) <= 2 &&
    typeof payload['message'] === 'string' && payload['message'].length <= 1024,
  'instrument.state': (payload) =>
    hasOnlyKeys(payload, ['instrument']) &&
    Number.isInteger(payload['instrument']) && (payload['instrument'] as number) >= 0 && (payload['instrument'] as number) <= 2,
  'sampler.state': (payload) =>
    hasOnlyKeys(payload, ['name', 'loaded', 'missing', 'loading', 'durationSeconds', 'overview']) &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['loaded'] === 'boolean' &&
    typeof payload['missing'] === 'boolean' &&
    typeof payload['loading'] === 'boolean' &&
    typeof payload['durationSeconds'] === 'number' && Number.isFinite(payload['durationSeconds']) && payload['durationSeconds'] >= 0 && payload['durationSeconds'] <= 100000 &&
    isNumberArray(payload['overview'], 0, 1, 512),
  'drums.pattern': (payload) =>
    hasOnlyKeys(payload, ['steps']) &&
    isNumberArray(payload['steps'], 0, 65535, 16),
  'drums.pad': (payload) =>
    hasOnlyKeys(payload, ['pad', 'name', 'volumeDb', 'pitch', 'muted', 'custom', 'missing']) &&
    Number.isInteger(payload['pad']) && (payload['pad'] as number) >= 0 && (payload['pad'] as number) <= 15 &&
    typeof payload['name'] === 'string' && payload['name'].length <= 256 &&
    typeof payload['volumeDb'] === 'number' && Number.isFinite(payload['volumeDb']) && payload['volumeDb'] >= -60 && payload['volumeDb'] <= 6 &&
    typeof payload['pitch'] === 'number' && Number.isFinite(payload['pitch']) && payload['pitch'] >= -24 && payload['pitch'] <= 24 &&
    typeof payload['muted'] === 'boolean' &&
    typeof payload['custom'] === 'boolean' &&
    typeof payload['missing'] === 'boolean',
};

/** Strictly validates a message received from native code. Returns null if it is malformed. */
export function parseNativeEvent(message: unknown): NativeEvent | null {
  if (!isPayload(message) || !hasOnlyKeys(message, ['type', 'payload'])) return null;
  const { type, payload } = message;
  if (typeof type !== 'string' || !Object.hasOwn(eventValidators, type) || !isPayload(payload)) return null;
  return eventValidators[type as NativeEventType](payload) ? (message as unknown as NativeEvent) : null;
}
