// GENERATED by tools/codegen/bridge.mjs from schema/bridge.json. DO NOT EDIT.

/* eslint-disable */

export const PROTOCOL_VERSION = 1;

// Intents: UI -> native
export interface AppReady {
  readonly type: 'app.ready';
  readonly payload: {};
}

export interface AudioOpenSettings {
  readonly type: 'audio.openSettings';
  readonly payload: {};
}

export interface ToneSetEnabled {
  readonly type: 'tone.setEnabled';
  readonly payload: {
    readonly enabled: boolean;
  };
}

export interface ToneSetLevel {
  readonly type: 'tone.setLevel';
  readonly payload: {
    readonly db: number;
  };
}

export type Intent = AppReady | AudioOpenSettings | ToneSetEnabled | ToneSetLevel;

// Events: native -> UI
export interface EngineStatus {
  readonly type: 'engine.status';
  readonly payload: {
    readonly deviceName: string;
    readonly sampleRate: number;
    readonly bufferSize: number;
    readonly outputLatencyMs: number;
    readonly error: string;
    readonly toneEnabled: boolean;
    readonly toneLevelDb: number;
  };
}

export interface EngineMeters {
  readonly type: 'engine.meters';
  readonly payload: {
    readonly peak: number;
  };
}

export type NativeEvent = EngineStatus | EngineMeters;
export type NativeEventType = NativeEvent['type'];

type Payload = Record<string, unknown>;

function isPayload(value: unknown): value is Payload {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(payload: Payload, keys: readonly string[]): boolean {
  const actual = Object.keys(payload);
  return actual.length === keys.length && keys.every((key) => Object.hasOwn(payload, key));
}

const eventValidators: Record<NativeEventType, (payload: Payload) => boolean> = {
  'engine.status': (payload) =>
    hasOnlyKeys(payload, ['deviceName', 'sampleRate', 'bufferSize', 'outputLatencyMs', 'error', 'toneEnabled', 'toneLevelDb']) &&
    typeof payload['deviceName'] === 'string' && payload['deviceName'].length <= 256 &&
    typeof payload['sampleRate'] === 'number' && Number.isFinite(payload['sampleRate']) && payload['sampleRate'] >= 0 && payload['sampleRate'] <= 768000 &&
    Number.isInteger(payload['bufferSize']) && (payload['bufferSize'] as number) >= 0 && (payload['bufferSize'] as number) <= 65536 &&
    typeof payload['outputLatencyMs'] === 'number' && Number.isFinite(payload['outputLatencyMs']) && payload['outputLatencyMs'] >= 0 && payload['outputLatencyMs'] <= 10000 &&
    typeof payload['error'] === 'string' && payload['error'].length <= 1024 &&
    typeof payload['toneEnabled'] === 'boolean' &&
    typeof payload['toneLevelDb'] === 'number' && Number.isFinite(payload['toneLevelDb']) && payload['toneLevelDb'] >= -60 && payload['toneLevelDb'] <= -6,
  'engine.meters': (payload) =>
    hasOnlyKeys(payload, ['peak']) &&
    typeof payload['peak'] === 'number' && Number.isFinite(payload['peak']) && payload['peak'] >= 0 && payload['peak'] <= 1,
};

/** Strictly validates a message received from native code. Returns null if it is malformed. */
export function parseNativeEvent(message: unknown): NativeEvent | null {
  if (!isPayload(message) || !hasOnlyKeys(message, ['type', 'payload'])) return null;
  const { type, payload } = message;
  if (typeof type !== 'string' || !Object.hasOwn(eventValidators, type) || !isPayload(payload)) return null;
  return eventValidators[type as NativeEventType](payload) ? (message as unknown as NativeEvent) : null;
}
