#!/usr/bin/env bash
# Signs, verifies and (when credentials are available) notarizes the macOS app, then zips it for
# distribution (plan Phase 6, decision D5).
#
#   tools/release/package-macos.sh [path/to/Audio Playground.app]
#
# Environment:
#   AP_SIGN_IDENTITY    "Developer ID Application: Name (TEAMID)". Unset: ad-hoc signature, for
#                       checking the hardened runtime locally (Gatekeeper will not accept it).
#   AP_NOTARY_PROFILE   notarytool keychain profile (xcrun notarytool store-credentials ...).
#                       Unset: no notarization.
#
# Output: dist/AudioPlayground-<version>-macos.zip
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
app="${1:-$root/build/release/apps/desktop/ap_desktop_artefacts/Release/Audio Playground.app}"
entitlements="$root/build/release/apps/desktop/ap_desktop_artefacts/JuceLibraryCode/ap_desktop.entitlements"
identity="${AP_SIGN_IDENTITY:-}"
profile="${AP_NOTARY_PROFILE:-}"

[[ -d "$app" ]] || { echo "No app at $app. Build it: cmake --preset release && cmake --build --preset release" >&2; exit 1; }
[[ -f "$entitlements" ]] || { echo "No entitlements at $entitlements (generated by the JUCE build)" >&2; exit 1; }

version="$(/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' "$app/Contents/Info.plist")"
mkdir -p "$root/dist"
zip="$root/dist/AudioPlayground-$version-macos.zip"

echo "Signing $app"
if [[ -n "$identity" ]]; then
    codesign --force --options runtime --timestamp --entitlements "$entitlements" --sign "$identity" "$app"
else
    echo "  (ad hoc: set AP_SIGN_IDENTITY to sign for distribution)"
    codesign --force --options runtime --entitlements "$entitlements" --sign - "$app"
fi

echo "Verifying"
codesign --verify --strict --deep --verbose=2 "$app"
codesign --display --verbose=2 "$app" 2>&1 | grep -E "flags=.*runtime" > /dev/null \
    || { echo "The hardened runtime is not enabled" >&2; exit 1; }
codesign --display --entitlements - "$app" 2>/dev/null | grep -q "com.apple.security.device.audio-input" \
    || { echo "The microphone entitlement is missing" >&2; exit 1; }

rm -f "$zip"
ditto -c -k --keepParent "$app" "$zip"

if [[ -n "$identity" && -n "$profile" ]]; then
    echo "Notarizing (this can take a few minutes)"
    xcrun notarytool submit "$zip" --keychain-profile "$profile" --wait
    xcrun stapler staple "$app"
    xcrun stapler validate "$app"
    spctl --assess --type execute --verbose=2 "$app"
    rm -f "$zip"
    ditto -c -k --keepParent "$app" "$zip" # again, with the ticket stapled
else
    echo "Not notarized (needs AP_SIGN_IDENTITY and AP_NOTARY_PROFILE)"
fi

echo "Done: $zip"
