#!/usr/bin/env node
// Generates the UI <-> native bridge code from schema/bridge.json (ADR-003).
//
//   node tools/codegen/bridge.mjs          write generated files
//   node tools/codegen/bridge.mjs --check  fail if generated files are out of date (CI)
//
// No dependencies on purpose: this script is part of the trusted build.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const schemaPath = join(root, 'schema', 'bridge.json');
const outputs = {
  cppMessages: join(root, 'core', 'include', 'ap', 'bridge', 'generated', 'Messages.h'),
  cppCodecHeader: join(root, 'apps', 'desktop', 'src', 'generated', 'BridgeCodec.h'),
  cppCodecSource: join(root, 'apps', 'desktop', 'src', 'generated', 'BridgeCodec.cpp'),
  ts: join(root, 'ui', 'src', 'bridge', 'generated.ts'),
};

const banner = (comment) =>
  `${comment} GENERATED by tools/codegen/bridge.mjs from schema/bridge.json. DO NOT EDIT.\n`;

// ---------------------------------------------------------------------------------------------
// Schema loading and validation

const FIELD_TYPES = new Set(['bool', 'int', 'number', 'string']);
const NAME_PATTERN = /^[a-z][a-zA-Z0-9]*\.[a-z][a-zA-Z0-9]*$/;
const FIELD_PATTERN = /^[a-z][a-zA-Z0-9]*$/;

function fail(message) {
  console.error(`bridge codegen: ${message}`);
  process.exit(1);
}

function loadSchema() {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8'));
  if (!Number.isInteger(schema.protocolVersion) || schema.protocolVersion < 1)
    fail('protocolVersion must be a positive integer');

  const messages = (kind) =>
    Object.entries(schema[kind] ?? {}).map(([name, fields]) => {
      if (!NAME_PATTERN.test(name)) fail(`${kind} name "${name}" must look like "domain.action"`);
      return {
        name,
        typeName: name
          .split('.')
          .map((part) => part[0].toUpperCase() + part.slice(1))
          .join(''),
        fields: Object.entries(fields).map(([fieldName, spec]) => {
          if (!FIELD_PATTERN.test(fieldName)) fail(`${name}.${fieldName}: invalid field name`);
          if (!FIELD_TYPES.has(spec.type)) fail(`${name}.${fieldName}: unknown type "${spec.type}"`);
          if (spec.type === 'string' && !Number.isInteger(spec.maxLength))
            fail(`${name}.${fieldName}: strings need maxLength`);
          if ((spec.type === 'int' || spec.type === 'number') && !(Number.isFinite(spec.min) && Number.isFinite(spec.max)))
            fail(`${name}.${fieldName}: numbers need finite min and max`);
          if (spec.min > spec.max) fail(`${name}.${fieldName}: min > max`);
          return { name: fieldName, ...spec };
        }),
      };
    });

  return { protocolVersion: schema.protocolVersion, intents: messages('intents'), events: messages('events') };
}

// ---------------------------------------------------------------------------------------------
// C++: JUCE-free message structs (core)

const cppType = { bool: 'bool', int: 'int', number: 'double', string: 'std::string' };
const cppDefault = { bool: 'false', int: '0', number: '0.0', string: '' };
const cppNumber = (value) => (Number.isInteger(value) ? `${value}.0` : `${value}`);

function cppStruct(message) {
  const lines = [`struct ${message.typeName}`, '{', `    static constexpr std::string_view type = "${message.name}";`];
  for (const field of message.fields) {
    if (field.type === 'int' || field.type === 'number') {
      const literal = field.type === 'int' ? (v) => `${v}` : cppNumber;
      lines.push(`    static constexpr ${cppType[field.type]} ${field.name}Min = ${literal(field.min)};`);
      lines.push(`    static constexpr ${cppType[field.type]} ${field.name}Max = ${literal(field.max)};`);
    }
    if (field.type === 'string') lines.push(`    static constexpr std::size_t ${field.name}MaxLength = ${field.maxLength};`);
  }
  if (message.fields.length > 0) lines.push('');
  for (const field of message.fields) {
    const init = cppDefault[field.type] === '' ? '{}' : ` = ${cppDefault[field.type]}`;
    lines.push(`    ${cppType[field.type]} ${field.name}${init === '{}' ? ' {}' : init};`);
  }
  lines.push('', `    bool operator== (const ${message.typeName}&) const = default;`, '};');
  return lines.join('\n');
}

function generateCppMessages(schema) {
  const all = [...schema.intents, ...schema.events];
  return `${banner('//')}
#pragma once

#include <cstddef>
#include <string>
#include <string_view>
#include <variant>

namespace ap::bridge
{

inline constexpr int protocolVersion = ${schema.protocolVersion};

${all.map(cppStruct).join('\n\n')}

using Intent = std::variant<${schema.intents.map((m) => m.typeName).join(', ')}>;
using Event = std::variant<${schema.events.map((m) => m.typeName).join(', ')}>;

} // namespace ap::bridge
`;
}

// ---------------------------------------------------------------------------------------------
// C++: juce::var codec (desktop adapter)

function cppFieldReader(message, field) {
  const target = `message.${field.name}`;
  const lookup = `payload->getProperty ("${field.name}")`;
  switch (field.type) {
    case 'bool':
      return `    if (!readBool (*payload, "${field.name}", ${target})) return std::nullopt;`;
    case 'int':
      return `    if (!readInt (*payload, "${field.name}", ${message.typeName}::${field.name}Min, ${message.typeName}::${field.name}Max, ${target})) return std::nullopt;`;
    case 'number':
      return `    if (!readNumber (*payload, "${field.name}", ${message.typeName}::${field.name}Min, ${message.typeName}::${field.name}Max, ${target})) return std::nullopt;`;
    case 'string':
      return `    if (!readString (*payload, "${field.name}", ${message.typeName}::${field.name}MaxLength, ${target})) return std::nullopt;`;
    default:
      return fail(`unhandled type ${field.type} (${lookup})`);
  }
}

function cppIntentParser(message) {
  const names = message.fields.map((f) => `"${f.name}"`).join(', ');
  return `std::optional<Intent> parse${message.typeName} (const juce::var& payloadVar)
{
    const auto* payload = payloadVar.getDynamicObject();
    if (payload == nullptr || !hasOnlyKeys (*payload, {${names}}))
        return std::nullopt;

    ${message.typeName} message;
${message.fields.map((f) => cppFieldReader(message, f)).join('\n')}
    return Intent {message};
}`;
}

function cppEventWriter(message) {
  const setters = message.fields
    .map((f) => {
      const value = f.type === 'string' ? `juce::String (m.${f.name})` : `m.${f.name}`;
      return `                payload->setProperty ("${f.name}", ${value});`;
    })
    .join('\n');
  return `            [] (const ${message.typeName}& m) -> juce::var
            {
                ${message.fields.length === 0 ? 'juce::ignoreUnused (m);\n                ' : ''}auto* payload = new juce::DynamicObject();
${setters}
                return envelope (${message.typeName}::type, payload);
            }`;
}

function generateCppCodec(schema) {
  const header = `${banner('//')}
#pragma once

#include "ap/bridge/generated/Messages.h"

#include <juce_core/juce_core.h>
#include <optional>

namespace ap::desktop::bridge
{

// Parses a UI intent of the form { "type": string, "payload": object }.
// Strict: unknown types, unknown or missing fields, wrong types, non-finite or out-of-range
// numbers and over-long strings are all rejected (std::nullopt). Never clamps.
[[nodiscard]] std::optional<ap::bridge::Intent> parseIntent (const juce::var& message);

// Serialises an event to { "type": string, "payload": object }.
[[nodiscard]] juce::var toVar (const ap::bridge::Event& event);

} // namespace ap::desktop::bridge
`;

  const source = `${banner('//')}
#include "BridgeCodec.h"

#include <cmath>
#include <initializer_list>

namespace ap::desktop::bridge
{
using namespace ap::bridge;

namespace
{
bool hasOnlyKeys (const juce::DynamicObject& object, std::initializer_list<const char*> allowed)
{
    const auto& properties = object.getProperties();
    if (properties.size() != static_cast<int> (allowed.size()))
        return false;

    for (const auto* key : allowed)
        if (!properties.contains (juce::Identifier (key)))
            return false;

    return true;
}

[[maybe_unused]] bool readBool (const juce::DynamicObject& object, const char* key, bool& out)
{
    const auto& value = object.getProperty (key);
    if (!value.isBool())
        return false;
    out = static_cast<bool> (value);
    return true;
}

[[maybe_unused]] bool readNumber (const juce::DynamicObject& object, const char* key, double min, double max, double& out)
{
    const auto& value = object.getProperty (key);
    if (!(value.isDouble() || value.isInt() || value.isInt64()))
        return false;
    const auto number = static_cast<double> (value);
    if (!std::isfinite (number) || number < min || number > max)
        return false;
    out = number;
    return true;
}

[[maybe_unused]] bool readInt (const juce::DynamicObject& object, const char* key, int min, int max, int& out)
{
    double number = 0.0;
    if (!readNumber (object, key, static_cast<double> (min), static_cast<double> (max), number)
        || std::floor (number) != number)
        return false;
    out = static_cast<int> (number);
    return true;
}

[[maybe_unused]] bool readString (const juce::DynamicObject& object, const char* key, std::size_t maxLength, std::string& out)
{
    const auto& value = object.getProperty (key);
    if (!value.isString())
        return false;
    const auto utf8 = value.toString().toStdString();
    if (utf8.size() > maxLength)
        return false;
    out = utf8;
    return true;
}

template <typename... Fns>
struct Overloaded : Fns...
{
    using Fns::operator()...;
};

juce::var envelope (std::string_view type, juce::DynamicObject* payload)
{
    auto* message = new juce::DynamicObject();
    message->setProperty ("type", juce::String (std::string (type)));
    message->setProperty ("payload", juce::var (payload));
    return juce::var (message);
}

${schema.intents.map(cppIntentParser).join('\n\n')}
} // namespace

std::optional<Intent> parseIntent (const juce::var& message)
{
    const auto* object = message.getDynamicObject();
    if (object == nullptr || !hasOnlyKeys (*object, {"type", "payload"}))
        return std::nullopt;

    const auto& type = object->getProperty ("type");
    if (!type.isString())
        return std::nullopt;

    const auto typeName = type.toString().toStdString();
    const auto& payload = object->getProperty ("payload");

${schema.intents.map((m) => `    if (typeName == ${m.typeName}::type)\n        return parse${m.typeName} (payload);`).join('\n')}

    return std::nullopt;
}

juce::var toVar (const Event& event)
{
    return std::visit (
        Overloaded {
${schema.events.map(cppEventWriter).join(',\n')}},
        event);
}

} // namespace ap::desktop::bridge
`;
  return { header, source };
}

// ---------------------------------------------------------------------------------------------
// TypeScript

const tsType = { bool: 'boolean', int: 'number', number: 'number', string: 'string' };

function tsInterface(message) {
  const fields = message.fields.map((f) => `    readonly ${f.name}: ${tsType[f.type]};`).join('\n');
  return `export interface ${message.typeName} {
  readonly type: '${message.name}';
  readonly payload: {${fields ? `\n${fields}\n  ` : ''}};
}`;
}

function tsFieldCheck(field) {
  const value = `payload['${field.name}']`;
  switch (field.type) {
    case 'bool':
      return `typeof ${value} === 'boolean'`;
    case 'int':
      return `Number.isInteger(${value}) && (${value} as number) >= ${field.min} && (${value} as number) <= ${field.max}`;
    case 'number':
      return `typeof ${value} === 'number' && Number.isFinite(${value}) && ${value} >= ${field.min} && ${value} <= ${field.max}`;
    case 'string':
      return `typeof ${value} === 'string' && ${value}.length <= ${field.maxLength}`;
    default:
      return fail(`unhandled type ${field.type}`);
  }
}

function tsEventValidator(message) {
  const keys = message.fields.map((f) => `'${f.name}'`).join(', ');
  const checks = message.fields.map((f) => `    ${tsFieldCheck(f)}`).join(' &&\n');
  return `  '${message.name}': (payload) =>
    hasOnlyKeys(payload, [${keys}])${checks ? ` &&\n${checks}` : ''},`;
}

function generateTs(schema) {
  return `${banner('//')}
/* eslint-disable */

export const PROTOCOL_VERSION = ${schema.protocolVersion};

// Intents: UI -> native
${schema.intents.map(tsInterface).join('\n\n')}

export type Intent = ${schema.intents.map((m) => m.typeName).join(' | ')};

// Events: native -> UI
${schema.events.map(tsInterface).join('\n\n')}

export type NativeEvent = ${schema.events.map((m) => m.typeName).join(' | ')};
export type NativeEventType = NativeEvent['type'];

/** Payload type for each native event type. */
export interface NativeEventPayloads {
${schema.events.map((m) => `  '${m.name}': ${m.typeName}['payload'];`).join('\n')}
}

type Payload = Record<string, unknown>;

function isPayload(value: unknown): value is Payload {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function hasOnlyKeys(payload: Payload, keys: readonly string[]): boolean {
  const actual = Object.keys(payload);
  return actual.length === keys.length && keys.every((key) => Object.hasOwn(payload, key));
}

const eventValidators: Record<NativeEventType, (payload: Payload) => boolean> = {
${schema.events.map(tsEventValidator).join('\n')}
};

/** Strictly validates a message received from native code. Returns null if it is malformed. */
export function parseNativeEvent(message: unknown): NativeEvent | null {
  if (!isPayload(message) || !hasOnlyKeys(message, ['type', 'payload'])) return null;
  const { type, payload } = message;
  if (typeof type !== 'string' || !Object.hasOwn(eventValidators, type) || !isPayload(payload)) return null;
  return eventValidators[type as NativeEventType](payload) ? (message as unknown as NativeEvent) : null;
}
`;
}

// ---------------------------------------------------------------------------------------------

const schema = loadSchema();
const codec = generateCppCodec(schema);
const files = new Map([
  [outputs.cppMessages, generateCppMessages(schema)],
  [outputs.cppCodecHeader, codec.header],
  [outputs.cppCodecSource, codec.source],
  [outputs.ts, generateTs(schema)],
]);

const check = process.argv.includes('--check');
let stale = false;

for (const [path, content] of files) {
  let current = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    current = null;
  }
  if (check) {
    if (current !== content) {
      console.error(`out of date: ${path}`);
      stale = true;
    }
  } else if (current !== content) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}

if (stale) fail('generated bridge files are out of date; run `pnpm codegen` and commit the result');
