#!/usr/bin/env node
// Generates parameter descriptors from schema/parameters.json (guide §16, ADR-003).
//
//   node tools/codegen/parameters.mjs          write generated files
//   node tools/codegen/parameters.mjs --check  fail if generated files are out of date (CI)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const schemaPath = join(root, 'schema', 'parameters.json');
const outputs = {
  cpp: join(root, 'core', 'include', 'ap', 'params', 'generated', 'ParameterIds.h'),
  ts: join(root, 'ui', 'src', 'params', 'generated.ts'),
};

const banner = '// GENERATED by tools/codegen/parameters.mjs from schema/parameters.json. DO NOT EDIT.\n';
const ID_PATTERN = /^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*)+$/;
const CURVES = new Set(['linear', 'logarithmic']);

function fail(message) {
  console.error(`parameter codegen: ${message}`);
  process.exit(1);
}

function load() {
  const { parameters } = JSON.parse(readFileSync(schemaPath, 'utf8'));
  if (!Array.isArray(parameters) || parameters.length === 0) fail('parameters must be a non-empty array');

  const seen = new Set();
  return parameters.map((p) => {
    if (!ID_PATTERN.test(p.id)) fail(`invalid id "${p.id}"`);
    if (seen.has(p.id)) fail(`duplicate id "${p.id}"`);
    seen.add(p.id);
    for (const key of ['min', 'max', 'default', 'step'])
      if (!Number.isFinite(p[key])) fail(`${p.id}: ${key} must be a finite number`);
    if (!(p.min < p.max)) fail(`${p.id}: min must be < max`);
    if (p.default < p.min || p.default > p.max) fail(`${p.id}: default out of range`);
    if (!(p.step > 0)) fail(`${p.id}: step must be > 0`);
    if (!CURVES.has(p.curve)) fail(`${p.id}: curve must be one of ${[...CURVES].join(', ')}`);
    if (p.curve === 'logarithmic' && p.min <= 0) fail(`${p.id}: logarithmic curves need min > 0`);
    if (typeof p.name !== 'string' || p.name.length === 0) fail(`${p.id}: name required`);
    if (typeof p.unit !== 'string') fail(`${p.id}: unit must be a string (may be empty)`);
    const enumName = p.id
      .split('.')
      .map((part) => part[0].toUpperCase() + part.slice(1))
      .join('');
    return { ...p, enumName: enumName[0].toLowerCase() + enumName.slice(1) };
  });
}

const cppFloat = (v) => (Number.isInteger(v) ? `${v}.0f` : `${v}f`);
const cppString = (s) => JSON.stringify(s);

function generateCpp(params) {
  return `${banner}
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

namespace ap::params
{

enum class Curve : std::uint8_t
{
    linear,
    logarithmic
};

struct ParameterDescriptor
{
    std::string_view id; // persistence contract
    std::string_view name;
    std::string_view unit;
    float min;
    float max;
    float defaultValue;
    float step;
    Curve curve;
};

enum class ParamId : std::uint16_t
{
${params.map((p) => `    ${p.enumName},`).join('\n')}
};

inline constexpr std::size_t numParameters = ${params.length};

inline constexpr std::array<ParameterDescriptor, numParameters> descriptors {{
${params
  .map(
    (p) =>
      `    {${cppString(p.id)}, ${cppString(p.name)}, ${cppString(p.unit)}, ${cppFloat(p.min)}, ${cppFloat(p.max)}, ${cppFloat(p.default)}, ${cppFloat(p.step)}, Curve::${p.curve}},`,
  )
  .join('\n')}
}};

} // namespace ap::params
`;
}

function generateTs(params) {
  return `${banner}
export type ParamId = ${params.map((p) => `'${p.id}'`).join(' | ')};

export interface ParameterDescriptor {
  readonly id: ParamId;
  readonly name: string;
  readonly unit: string;
  readonly min: number;
  readonly max: number;
  readonly defaultValue: number;
  readonly step: number;
  readonly curve: 'linear' | 'logarithmic';
}

export const PARAMETERS: Readonly<Record<ParamId, ParameterDescriptor>> = {
${params
  .map(
    (p) =>
      `  '${p.id}': { id: '${p.id}', name: ${JSON.stringify(p.name)}, unit: ${JSON.stringify(p.unit)}, min: ${p.min}, max: ${p.max}, defaultValue: ${p.default}, step: ${p.step}, curve: '${p.curve}' },`,
  )
  .join('\n')}
};

export function isParamId(value: unknown): value is ParamId {
  return typeof value === 'string' && Object.hasOwn(PARAMETERS, value);
}
`;
}

const params = load();
const files = new Map([
  [outputs.cpp, generateCpp(params)],
  [outputs.ts, generateTs(params)],
]);

const check = process.argv.includes('--check');
let stale = false;
for (const [path, content] of files) {
  let current = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    current = null;
  }
  if (current === content) continue;
  if (check) {
    console.error(`out of date: ${path}`);
    stale = true;
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${path}`);
  }
}
if (stale) fail('generated parameter files are out of date; run `pnpm codegen` and commit the result');
