// GENERATED by tools/codegen/parameters.mjs from schema/parameters.json. DO NOT EDIT.

export type ParamId = 'tone.level' | 'metronome.level' | 'synth.waveform' | 'synth.pitch' | 'synth.detune' | 'synth.cutoff' | 'synth.resonance' | 'synth.attack' | 'synth.decay' | 'synth.sustain' | 'synth.release' | 'synth.volume';

export interface ParameterDescriptor {
  readonly id: ParamId;
  readonly name: string;
  readonly unit: string;
  readonly min: number;
  readonly max: number;
  readonly defaultValue: number;
  readonly step: number;
  readonly curve: 'linear' | 'logarithmic';
}

export const PARAMETERS: Readonly<Record<ParamId, ParameterDescriptor>> = {
  'tone.level': { id: 'tone.level', name: "Test tone level", unit: "dB", min: -60, max: -6, defaultValue: -18, step: 0.5, curve: 'linear' },
  'metronome.level': { id: 'metronome.level', name: "Click level", unit: "dB", min: -60, max: 0, defaultValue: -12, step: 0.5, curve: 'linear' },
  'synth.waveform': { id: 'synth.waveform', name: "Waveform", unit: "", min: 0, max: 3, defaultValue: 2, step: 1, curve: 'linear' },
  'synth.pitch': { id: 'synth.pitch', name: "Pitch", unit: "st", min: -24, max: 24, defaultValue: 0, step: 1, curve: 'linear' },
  'synth.detune': { id: 'synth.detune', name: "Detune", unit: "ct", min: 0, max: 50, defaultValue: 8, step: 0.5, curve: 'linear' },
  'synth.cutoff': { id: 'synth.cutoff', name: "Brightness", unit: "Hz", min: 40, max: 18000, defaultValue: 4000, step: 1, curve: 'logarithmic' },
  'synth.resonance': { id: 'synth.resonance', name: "Resonance", unit: "", min: 0.5, max: 10, defaultValue: 0.8, step: 0.01, curve: 'logarithmic' },
  'synth.attack': { id: 'synth.attack', name: "Attack", unit: "s", min: 0.001, max: 5, defaultValue: 0.005, step: 0.001, curve: 'logarithmic' },
  'synth.decay': { id: 'synth.decay', name: "Decay", unit: "s", min: 0.001, max: 5, defaultValue: 0.3, step: 0.001, curve: 'logarithmic' },
  'synth.sustain': { id: 'synth.sustain', name: "Sustain", unit: "", min: 0, max: 1, defaultValue: 0.6, step: 0.01, curve: 'linear' },
  'synth.release': { id: 'synth.release', name: "Release", unit: "s", min: 0.001, max: 10, defaultValue: 0.4, step: 0.001, curve: 'logarithmic' },
  'synth.volume': { id: 'synth.volume', name: "Volume", unit: "dB", min: -60, max: 0, defaultValue: -12, step: 0.5, curve: 'linear' },
};

export function isParamId(value: unknown): value is ParamId {
  return typeof value === 'string' && Object.hasOwn(PARAMETERS, value);
}
