// GENERATED by tools/codegen/parameters.mjs from schema/parameters.json. DO NOT EDIT.

export type ParamId = 'tone.level' | 'metronome.level';

export interface ParameterDescriptor {
  readonly id: ParamId;
  readonly name: string;
  readonly unit: string;
  readonly min: number;
  readonly max: number;
  readonly defaultValue: number;
  readonly step: number;
  readonly curve: 'linear' | 'logarithmic';
}

export const PARAMETERS: Readonly<Record<ParamId, ParameterDescriptor>> = {
  'tone.level': { id: 'tone.level', name: "Test tone level", unit: "dB", min: -60, max: -6, defaultValue: -18, step: 0.5, curve: 'linear' },
  'metronome.level': { id: 'metronome.level', name: "Click level", unit: "dB", min: -60, max: 0, defaultValue: -12, step: 0.5, curve: 'linear' },
};

export function isParamId(value: unknown): value is ParamId {
  return typeof value === 'string' && Object.hasOwn(PARAMETERS, value);
}
