# Embeds every file under INPUT_DIR into a C++ source file (OUTPUT) as byte arrays.
# Run as a script: cmake -DINPUT_DIR=... -DOUTPUT=... -DNAMESPACE=... -P EmbedDirectory.cmake
#
# The generated table is the only source of UI files at run time: the WebView resource provider
# serves from it, so nothing is read from disk or the network.

cmake_minimum_required(VERSION 3.25)

foreach(var INPUT_DIR OUTPUT NAMESPACE)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "EmbedDirectory.cmake: ${var} is required")
    endif()
endforeach()

if(NOT IS_DIRECTORY "${INPUT_DIR}")
    message(FATAL_ERROR "EmbedDirectory.cmake: ${INPUT_DIR} does not exist (did the UI build run?)")
endif()

file(GLOB_RECURSE files LIST_DIRECTORIES FALSE RELATIVE "${INPUT_DIR}" "${INPUT_DIR}/*")
list(SORT files)

if(NOT files)
    message(FATAL_ERROR "EmbedDirectory.cmake: ${INPUT_DIR} is empty")
endif()

set(arrays "")
set(entries "")
set(index 0)

foreach(file IN LISTS files)
    file(READ "${INPUT_DIR}/${file}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND arrays "constexpr unsigned char file${index}[] = {${bytes}};\n")
    string(APPEND entries "    {\"${file}\", file${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUTPUT}.tmp" "// GENERATED by cmake/EmbedDirectory.cmake. DO NOT EDIT.
#include \"EmbeddedResources.h\"

namespace ${NAMESPACE}
{
namespace
{
${arrays}
constexpr EmbeddedFile table[] = {
${entries}};
} // namespace

std::span<const EmbeddedFile> embeddedFiles() noexcept
{
    return table;
}

} // namespace ${NAMESPACE}
")

file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
